### ISSUE TITLE
Seader

### ISSUE THREAD

**Issue by NewStarAI** [bettse/seader#1]
Hi all Im following the seader hardware guide but need guidance for connecting the click board to flipper. Thank you

**Comment by bettse** [comment]
Can you be more specific?  Did you attempt it and not see the results you expected, or have you not tried it yet?  There is a certain level of hardware experience expected for this: do you already have experience with hooking up external components on an Arduino or similar?

**Comment by NewStarAI** [comment]
Hi yes, with Connections, GND is connected to all three "8/11/18" or is it to only one of these three points?

**Comment by bettse** [comment]
If you consult the Flipper Zero GPIO documentation you'll see all three are labeled as ground, so those are the 3 options you may choose from.
