### ISSUE TITLE
Better understanding purpose of this flipper app

### ISSUE THREAD

**Issue by ezhang7423** [bettse/seader#5]
Hi there,

Thank you for your hard work on this repository. I would like to better understand what a SAM is and what capabilities this repo gives if I were to buy the hardware linked on the readme. I am especially curious about whether I would be able to emulate a HID iClass SE.

Thanks again for the time and consideration.

**Comment by bettse** [comment]
A sam is a way of storing secrets (https://en.wikipedia.org/wiki/Secure_access_module).  You can see a description of what Seader does in the app catalog: https://lab.flipper.net/apps/seader.  It does not provide _any_  emulation.

**Comment by ezhang7423** [comment]
I see, thank you very much for the info. Looking at your description:
"Allows for reading credential from HID iClass, iClass SE, Desfire EV1, and Seos. Credentials can be saved in an agnostic format, or **as various Flipper formats (Prox, MFC, iClass, iClass SR),** depending on the original type.
Requires addon: UART to mini-SIM adapter and HID SAM."

If I did want to perform emulation, would I be able to save the keys on a HID iClass SE card into another format, and emulate in other applications? If not, are there any other paths you would recommend looking into?

**Comment by bettse** [comment]
> would I be able to save the keys on a HID iClass SE card into another format,

Thats what it says :+1:.  This is called a "downgrade attack".  Whether it works or not will depend on the configuration of the reader you're emulating to.
