### ISSUE TITLE
Update the Seader app for the SDK version 0.98.2-rc f7

### ISSUE THREAD

**Issue by furippa** [bettse/seader#8]
Hello! Your Seader app version 2.3 fails to build with the SDK version 0.98.2-rc f7. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/649aed4e4cc7a7b78308d752/page)

**Comment by bettse** [comment]
try now

**Comment by bettse** [comment]
https://github.com/flipperdevices/flipper-application-catalog/pull/265
